/* Generated by AN DISI Unibo */ 
package it.unibo.sonarwrapper

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonarwrapper ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		val DFREE = 30
			  var isOutOfService = false 
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						connectToMqttBroker( "tcp://mosquitto:1883" )
						subscribe(  "sonar/data" ) //mqtt.subscribe(this,topic)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t015",targetState="handleDistance",cond=whenDispatch("sonardata"))
				}	 
				state("handleDistance") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("sonardata(Distance)"), Term.createTerm("sonardata(Distance)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								val distance = "${payloadArg(0)}".toDouble() 
								if( !isOutOfService && distance > DFREE 
								 ){isOutOfService = true 
								CommUtils.outblue("$name | Out of service")
								emit("outOfService", "outOfService(OutOfService)" ) 
								}
								if( isOutOfService && distance < DFREE 
								 ){isOutOfService = false 
								CommUtils.outblue("$name | Service working")
								emit("serviceWorking", "serviceWorking(ServiceWorking)" ) 
								}
								if( distance < DFREE / 2 
								 ){CommUtils.outblue("$name | Container deposited")
								emit("iOPortDeposited", "iOPortDeposited(DepositedToIOPort)" ) 
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t016",targetState="handleDistance",cond=whenDispatch("sonardata"))
					transition(edgeName="t017",targetState="handleBlinkLed",cond=whenDispatch("blinkLed"))
				}	 
				state("handleBlinkLed") { //this:State
					action { //it:State
						CommUtils.outblue("$name | Forwarding blinkLed to sonar")
						if( checkMsgContent( Term.createTerm("blinkLed(Blink)"), Term.createTerm("blinkLed(Status)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val msg = MsgUtil.buildDispatch(name, "blinkLed", "blinkLed(${payloadArg(0)})", "sonar")
									 		   println("Sending " + msg.toString())
									 		   mqtt.publish("sonar/led", msg.toString()) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t018",targetState="handleDistance",cond=whenDispatch("sonardata"))
					transition(edgeName="t019",targetState="handleBlinkLed",cond=whenDispatch("blinkLed"))
				}	 
			}
		}
} 
