/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "disengaged"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		val TimeoutMillis = 30000
			  var IOPortOccupied = false
			  var NSlotsOccupied = 0
			  var IsEngaged = false 
		return { //this:ActionBasciFsm
				state("disengaged") { //this:State
					action { //it:State
						IsEngaged = false 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleRequest",cond=whenRequest("loadRequest"))
				}	 
				state("handleRequest") { //this:State
					action { //it:State
						if(  IOPortOccupied  
						 ){answer("loadRequest", "retryLater", "retryLater(IOPortOccupied)"   )  
						}
						if(  NSlotsOccupied == 5  
						 ){answer("loadRequest", "rejected", "rejected(AllSlotsFull)"   )  
						}
						IsEngaged = true 
						NSlotsOccupied++ 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engaged", cond=doswitchGuarded({IsEngaged 
					}) )
					transition( edgeName="goto",targetState="disengaged", cond=doswitchGuarded({! (IsEngaged 
					) }) )
				}	 
				state("engaged") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_engaged", 
				 	 					  scope, context!!, "local_tout_"+name+"_engaged", TimeoutMillis )  //OCT2023
					}	 	 
					 transition(edgeName="t01",targetState="disengaged",cond=whenTimeout("local_tout_"+name+"_engaged"))   
					transition(edgeName="t02",targetState="moveRobot",cond=whenDispatch("iOPortDeposited"))
				}	 
				state("moveRobot") { //this:State
					action { //it:State
						request("markContainer", "markContainer(Id)" ,"marker" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="finishMoveRobot",cond=whenReply("markDone"))
				}	 
				state("finishMoveRobot") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
			}
		}
} 
