/* Generated by AN DISI Unibo */ 
package it.unibo.ioportadapter

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Ioportadapter ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 var listenerConn : unibo.basicomm23.interfaces.Interaction? = null  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | Started")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="handleRegister",cond=whenRequest("registerListener"))
				}	 
				state("handleRegister") { //this:State
					action { //it:State
						CommUtils.outblue("$name | TCP Event Listener registered successfully: $listenerConn")
						listenerConn = currentMsg.conn 
						answer("registerListener", "registered", "registered(ok)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t09",targetState="handleRegister",cond=whenRequest("registerListener"))
					transition(edgeName="t010",targetState="handleOutOfService",cond=whenEvent("outOfService"))
					transition(edgeName="t011",targetState="handleServiceWorking",cond=whenEvent("serviceWorking"))
				}	 
				state("handleOutOfService") { //this:State
					action { //it:State
						CommUtils.outblue("$name | Handling out of service")
						if (listenerConn != null) {
								      val msg = unibo.basicomm23.msg.ApplMessage("msg(outOfServiceMsg, dispatch, $name, ioport, outOfService(OutOfService), 1)")
								      listenerConn?.forward(msg)
								  } 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t012",targetState="handleRegister",cond=whenRequest("registerListener"))
					transition(edgeName="t013",targetState="handleOutOfService",cond=whenEvent("outOfService"))
					transition(edgeName="t014",targetState="handleServiceWorking",cond=whenEvent("serviceWorking"))
				}	 
				state("handleServiceWorking") { //this:State
					action { //it:State
						CommUtils.outblue("$name | Handling service working")
						if (listenerConn != null) {
								      val msg = unibo.basicomm23.msg.ApplMessage("msg(serviceWorkingMsg, dispatch, $name, ioport, serviceWorking(ServiceWorking), 1)")
								      listenerConn?.forward(msg)
								  } 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t015",targetState="handleRegister",cond=whenRequest("registerListener"))
					transition(edgeName="t016",targetState="handleOutOfService",cond=whenEvent("outOfService"))
					transition(edgeName="t017",targetState="handleServiceWorking",cond=whenEvent("serviceWorking"))
				}	 
			}
		}
} 
